/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    GiraffeNFT: {
      address: "0x700b6a60ce7eaaea56f065753d8dcb9653dbad35",
      abi: [
        {
          type: "constructor",
          inputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "approve",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "balanceOf",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "baseTokenURI",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "conditioningOf",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "decreaseReadiness",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getApproved",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isApprovedForAll",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
            {
              name: "operator",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "mint",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "mint",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "giraffeName",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "mint",
          inputs: [
            {
              name: "giraffeName",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "mintWithReadiness",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "readiness",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "giraffeName",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "name",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "nameOf",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "nextTokenId",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "ownerOf",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "raceContract",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "readinessOf",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "safeTransferFrom",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "safeTransferFrom",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "data",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "seedOf",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "setApprovalForAll",
          inputs: [
            {
              name: "operator",
              type: "address",
              internalType: "address",
            },
            {
              name: "approved",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setBaseTokenURI",
          inputs: [
            {
              name: "newBaseTokenURI",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setForTesting",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "readiness",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "conditioning",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "speed",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setRaceContract",
          inputs: [
            {
              name: "_race",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setReadinessForTesting",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "readiness",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "speedOf",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "statsOf",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "readiness",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "conditioning",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "speed",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "supportsInterface",
          inputs: [
            {
              name: "interfaceId",
              type: "bytes4",
              internalType: "bytes4",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "symbol",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "tokenURI",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "tokensOfOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transferFrom",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "Approval",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "approved",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ApprovalForAll",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "operator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "approved",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "BaseTokenURISet",
          inputs: [
            {
              name: "baseTokenURI",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "GiraffeMinted",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "seed",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
            {
              name: "name",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Transfer",
          inputs: [
            {
              name: "from",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "ERC721IncorrectOwner",
          inputs: [
            {
              name: "sender",
              type: "address",
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC721InsufficientApproval",
          inputs: [
            {
              name: "operator",
              type: "address",
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "ERC721InvalidApprover",
          inputs: [
            {
              name: "approver",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC721InvalidOperator",
          inputs: [
            {
              name: "operator",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC721InvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC721InvalidReceiver",
          inputs: [
            {
              name: "receiver",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC721InvalidSender",
          inputs: [
            {
              name: "sender",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC721NonexistentToken",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 1,
    },
    WinProbTable: {
      address: "0xa15bb66138824a1c7167f5e85b957d04dd34e468",
      abi: [
        {
          type: "function",
          name: "getSorted",
          inputs: [
            {
              name: "a",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "b",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "c",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "d",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          outputs: [
            {
              name: "probsBps",
              type: "uint16[4]",
              internalType: "uint16[4]",
            },
          ],
          stateMutability: "pure",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 2,
    },
    GiraffeRaceSimulator: {
      address: "0xb19b36b1456e65e3a6d514d3f715f204bd59f431",
      abi: [
        {
          type: "function",
          name: "simulate",
          inputs: [
            {
              name: "seed",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "winner",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "distances",
              type: "uint16[4]",
              internalType: "uint16[4]",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "simulateWithScore",
          inputs: [
            {
              name: "seed",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "scores",
              type: "uint8[4]",
              internalType: "uint8[4]",
            },
          ],
          outputs: [
            {
              name: "winner",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "distances",
              type: "uint16[4]",
              internalType: "uint16[4]",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "winnerWithScore",
          inputs: [
            {
              name: "seed",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "scores",
              type: "uint8[4]",
              internalType: "uint8[4]",
            },
          ],
          outputs: [
            {
              name: "winner",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "pure",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 4,
    },
    GiraffeRace: {
      address: "0xed1db453c3156ff3155a97ad217b3087d5dc5f6e",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_giraffeNft",
              type: "address",
              internalType: "address",
            },
            {
              name: "_house",
              type: "address",
              internalType: "address",
            },
            {
              name: "_houseGiraffeTokenIds",
              type: "uint256[4]",
              internalType: "uint256[4]",
            },
            {
              name: "_winProbTable",
              type: "address",
              internalType: "address",
            },
            {
              name: "_simulator",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "receive",
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "HOUSE_EDGE_BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint16",
              internalType: "uint16",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "LANE_COUNT",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MAX_ENTRIES_PER_RACE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint16",
              internalType: "uint16",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MAX_TICKS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint16",
              internalType: "uint16",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "SPEED_RANGE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "TRACK_LENGTH",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint16",
              internalType: "uint16",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "claim",
          inputs: [],
          outputs: [
            {
              name: "payout",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "claimNextWinningPayout",
          inputs: [],
          outputs: [
            {
              name: "payout",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "createRace",
          inputs: [],
          outputs: [
            {
              name: "raceId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "finalizeRaceGiraffes",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getBet",
          inputs: [
            {
              name: "bettor",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "amount",
              type: "uint128",
              internalType: "uint128",
            },
            {
              name: "lane",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "claimed",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getBetById",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "bettor",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "amount",
              type: "uint128",
              internalType: "uint128",
            },
            {
              name: "lane",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "claimed",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getClaimRemaining",
          inputs: [
            {
              name: "bettor",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "remaining",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getNextClaim",
          inputs: [
            {
              name: "bettor",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "out",
              type: "tuple",
              internalType: "struct GiraffeRace.NextClaimView",
              components: [
                {
                  name: "hasClaim",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "raceId",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "status",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "betLane",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "betTokenId",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "betAmount",
                  type: "uint128",
                  internalType: "uint128",
                },
                {
                  name: "winner",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "payout",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "closeBlock",
                  type: "uint64",
                  internalType: "uint64",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getNextWinningClaim",
          inputs: [
            {
              name: "bettor",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "out",
              type: "tuple",
              internalType: "struct GiraffeRace.NextClaimView",
              components: [
                {
                  name: "hasClaim",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "raceId",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "status",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "betLane",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "betTokenId",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "betAmount",
                  type: "uint128",
                  internalType: "uint128",
                },
                {
                  name: "winner",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "payout",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "closeBlock",
                  type: "uint64",
                  internalType: "uint64",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRace",
          inputs: [],
          outputs: [
            {
              name: "closeBlock",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "settled",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "winner",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "seed",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "totalPot",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalOnLane",
              type: "uint256[4]",
              internalType: "uint256[4]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRaceById",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "closeBlock",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "settled",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "winner",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "seed",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "totalPot",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalOnLane",
              type: "uint256[4]",
              internalType: "uint256[4]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRaceGiraffes",
          inputs: [],
          outputs: [
            {
              name: "assignedCount",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "tokenIds",
              type: "uint256[4]",
              internalType: "uint256[4]",
            },
            {
              name: "originalOwners",
              type: "address[4]",
              internalType: "address[4]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRaceGiraffesById",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "assignedCount",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "tokenIds",
              type: "uint256[4]",
              internalType: "uint256[4]",
            },
            {
              name: "originalOwners",
              type: "address[4]",
              internalType: "address[4]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRaceOddsById",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "oddsSet",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "decimalOddsBps",
              type: "uint32[4]",
              internalType: "uint32[4]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRaceScore",
          inputs: [],
          outputs: [
            {
              name: "score",
              type: "uint8[4]",
              internalType: "uint8[4]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRaceScoreById",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "score",
              type: "uint8[4]",
              internalType: "uint8[4]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getWinningClaimRemaining",
          inputs: [
            {
              name: "bettor",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "remaining",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "giraffeNft",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IGiraffeNFT",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "house",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "houseGiraffeTokenIds",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "laneCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "latestRaceId",
          inputs: [],
          outputs: [
            {
              name: "raceId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "nextRaceId",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "placeBet",
          inputs: [
            {
              name: "lane",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "setRaceOdds",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "decimalOddsBps",
              type: "uint32[4]",
              internalType: "uint32[4]",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "settleRace",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "settledLiability",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "simulate",
          inputs: [
            {
              name: "seed",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "winner",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "distances",
              type: "uint16[4]",
              internalType: "uint16[4]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "simulateWithScore",
          inputs: [
            {
              name: "seed",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "score",
              type: "uint8[4]",
              internalType: "uint8[4]",
            },
          ],
          outputs: [
            {
              name: "winner",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "distances",
              type: "uint16[4]",
              internalType: "uint16[4]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "simulator",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract GiraffeRaceSimulator",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "speedRange",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "submitGiraffe",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "tickCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint16",
              internalType: "uint16",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "trackLength",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint16",
              internalType: "uint16",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "winProbTable",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract WinProbTable",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "event",
          name: "BetPlaced",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "bettor",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "lane",
              type: "uint8",
              indexed: true,
              internalType: "uint8",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Claimed",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "bettor",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "payout",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "GiraffeAssigned",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "tokenId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "originalOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "lane",
              type: "uint8",
              indexed: false,
              internalType: "uint8",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "GiraffeSubmitted",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "lane",
              type: "uint8",
              indexed: false,
              internalType: "uint8",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "HouseGiraffeAssigned",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "tokenId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "lane",
              type: "uint8",
              indexed: false,
              internalType: "uint8",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "RaceCreated",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "closeBlock",
              type: "uint64",
              indexed: false,
              internalType: "uint64",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "RaceOddsSet",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "odds0Bps",
              type: "uint32",
              indexed: false,
              internalType: "uint32",
            },
            {
              name: "odds1Bps",
              type: "uint32",
              indexed: false,
              internalType: "uint32",
            },
            {
              name: "odds2Bps",
              type: "uint32",
              indexed: false,
              internalType: "uint32",
            },
            {
              name: "odds3Bps",
              type: "uint32",
              indexed: false,
              internalType: "uint32",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "RaceSettled",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "seed",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
            {
              name: "winner",
              type: "uint8",
              indexed: false,
              internalType: "uint8",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "AlreadyBet",
          inputs: [],
        },
        {
          type: "error",
          name: "AlreadyClaimed",
          inputs: [],
        },
        {
          type: "error",
          name: "AlreadySettled",
          inputs: [],
        },
        {
          type: "error",
          name: "AlreadySubmitted",
          inputs: [],
        },
        {
          type: "error",
          name: "BettingClosed",
          inputs: [],
        },
        {
          type: "error",
          name: "BettingNotOpen",
          inputs: [],
        },
        {
          type: "error",
          name: "BlockhashUnavailable",
          inputs: [],
        },
        {
          type: "error",
          name: "EntryPoolFull",
          inputs: [],
        },
        {
          type: "error",
          name: "GiraffeNotAssigned",
          inputs: [],
        },
        {
          type: "error",
          name: "GiraffesAlreadyFinalized",
          inputs: [],
        },
        {
          type: "error",
          name: "InsufficientBankroll",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidHouseGiraffe",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidLane",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidOdds",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidRace",
          inputs: [],
        },
        {
          type: "error",
          name: "NoClaimableBets",
          inputs: [],
        },
        {
          type: "error",
          name: "NotHouse",
          inputs: [],
        },
        {
          type: "error",
          name: "NotSettled",
          inputs: [],
        },
        {
          type: "error",
          name: "NotTokenOwner",
          inputs: [],
        },
        {
          type: "error",
          name: "NotWinner",
          inputs: [],
        },
        {
          type: "error",
          name: "OddsAlreadySet",
          inputs: [],
        },
        {
          type: "error",
          name: "OddsNotSet",
          inputs: [],
        },
        {
          type: "error",
          name: "PreviousRaceNotSettled",
          inputs: [],
        },
        {
          type: "error",
          name: "RaceNotReady",
          inputs: [],
        },
        {
          type: "error",
          name: "SubmissionsClosed",
          inputs: [],
        },
        {
          type: "error",
          name: "TokenAlreadyEntered",
          inputs: [],
        },
        {
          type: "error",
          name: "TransferFailed",
          inputs: [],
        },
        {
          type: "error",
          name: "ZeroBet",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 4,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
