/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    MockUSDC: {
      address: "0x700b6a60ce7eaaea56f065753d8dcb9653dbad35",
      abi: [
        {
          type: "constructor",
          inputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "allowance",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "approve",
          inputs: [
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "balanceOf",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "decimals",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "faucet",
          inputs: [
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "mint",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "name",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "symbol",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "totalSupply",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transfer",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferFrom",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "Approval",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "spender",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Transfer",
          inputs: [
            {
              name: "from",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "ERC20InsufficientAllowance",
          inputs: [
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
            {
              name: "allowance",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "needed",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InsufficientBalance",
          inputs: [
            {
              name: "sender",
              type: "address",
              internalType: "address",
            },
            {
              name: "balance",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "needed",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidApprover",
          inputs: [
            {
              name: "approver",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidReceiver",
          inputs: [
            {
              name: "receiver",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidSender",
          inputs: [
            {
              name: "sender",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidSpender",
          inputs: [
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 1,
    },
    HouseTreasury: {
      address: "0xb19b36b1456e65e3a6d514d3f715f204bd59f431",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_usdc",
              type: "address",
              internalType: "address",
            },
            {
              name: "_owner",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "authorize",
          inputs: [
            {
              name: "contractAddr",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "authorizedContracts",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "balance",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "collectBet",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "deauthorize",
          inputs: [
            {
              name: "contractAddr",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "deposit",
          inputs: [
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "pause",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "paused",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "payWinner",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "unpause",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "usdc",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IERC20",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "withdraw",
          inputs: [
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "withdrawAll",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "BetCollected",
          inputs: [
            {
              name: "from",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "collector",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ContractAuthorized",
          inputs: [
            {
              name: "contractAddr",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ContractDeauthorized",
          inputs: [
            {
              name: "contractAddr",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Deposited",
          inputs: [
            {
              name: "from",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Paused",
          inputs: [
            {
              name: "by",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Unpaused",
          inputs: [
            {
              name: "by",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "WinnerPaid",
          inputs: [
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "payer",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Withdrawn",
          inputs: [
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "IsPaused",
          inputs: [],
        },
        {
          type: "error",
          name: "NotAuthorized",
          inputs: [],
        },
        {
          type: "error",
          name: "NotOwner",
          inputs: [],
        },
        {
          type: "error",
          name: "TransferFailed",
          inputs: [],
        },
        {
          type: "error",
          name: "ZeroAddress",
          inputs: [],
        },
        {
          type: "error",
          name: "ZeroAmount",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 2,
    },
    GiraffeNFT: {
      address: "0x8ce361602b935680e8dec218b820ff5056beb7af",
      abi: [
        {
          type: "constructor",
          inputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "MAX_REVEAL_BLOCKS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MIN_REVEAL_BLOCKS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "approve",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "balanceOf",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "baseTokenURI",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "cancelCommit",
          inputs: [
            {
              name: "commitId",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "commitMint",
          inputs: [
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "commitment",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "commitId",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "conditioningOf",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "decreaseReadiness",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getApproved",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getCommit",
          inputs: [
            {
              name: "commitId",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "minter",
              type: "address",
              internalType: "address",
            },
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "blockNumber",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "status",
              type: "uint8",
              internalType: "enum GiraffeNFT.CommitStatus",
            },
            {
              name: "minRevealBlock",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "maxRevealBlock",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getPendingCommits",
          inputs: [
            {
              name: "user",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32[]",
              internalType: "bytes32[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getUserCommits",
          inputs: [
            {
              name: "user",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32[]",
              internalType: "bytes32[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isApprovedForAll",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
            {
              name: "operator",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isNameAvailable",
          inputs: [
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "available",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "mint",
          inputs: [
            {
              name: "giraffeName",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "mintCommits",
          inputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "minter",
              type: "address",
              internalType: "address",
            },
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "commitment",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "blockNumber",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "status",
              type: "uint8",
              internalType: "enum GiraffeNFT.CommitStatus",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "mintTo",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "giraffeName",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "mintWithReadiness",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "readiness",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "giraffeName",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "name",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "nameOf",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "nextTokenId",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "ownerOf",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "raceContract",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "readinessOf",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "releaseExpiredCommit",
          inputs: [
            {
              name: "commitId",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "revealMint",
          inputs: [
            {
              name: "commitId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "secret",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "safeTransferFrom",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "safeTransferFrom",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "data",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "seedOf",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "setApprovalForAll",
          inputs: [
            {
              name: "operator",
              type: "address",
              internalType: "address",
            },
            {
              name: "approved",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setBaseTokenURI",
          inputs: [
            {
              name: "newBaseTokenURI",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setForTesting",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "readiness",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "conditioning",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "speed",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setRaceContract",
          inputs: [
            {
              name: "_race",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setReadinessForTesting",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "readiness",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "speedOf",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "statsOf",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "readiness",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "conditioning",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "speed",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "supportsInterface",
          inputs: [
            {
              name: "interfaceId",
              type: "bytes4",
              internalType: "bytes4",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "symbol",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "tokenURI",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "tokensOfOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transferFrom",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "Approval",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "approved",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ApprovalForAll",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "operator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "approved",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "BaseTokenURISet",
          inputs: [
            {
              name: "baseTokenURI",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "GiraffeMinted",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "seed",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
            {
              name: "name",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "MintCommitCancelled",
          inputs: [
            {
              name: "commitId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "minter",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "MintCommitted",
          inputs: [
            {
              name: "commitId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "minter",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "name",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "blockNumber",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "MintRevealed",
          inputs: [
            {
              name: "commitId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "tokenId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "minter",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Transfer",
          inputs: [
            {
              name: "from",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "BlockhashUnavailable",
          inputs: [],
        },
        {
          type: "error",
          name: "CommitExpired",
          inputs: [
            {
              name: "currentBlock",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "expiryBlock",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "CommitNotFound",
          inputs: [],
        },
        {
          type: "error",
          name: "CommitNotPending",
          inputs: [],
        },
        {
          type: "error",
          name: "ERC721IncorrectOwner",
          inputs: [
            {
              name: "sender",
              type: "address",
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC721InsufficientApproval",
          inputs: [
            {
              name: "operator",
              type: "address",
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "ERC721InvalidApprover",
          inputs: [
            {
              name: "approver",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC721InvalidOperator",
          inputs: [
            {
              name: "operator",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC721InvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC721InvalidReceiver",
          inputs: [
            {
              name: "receiver",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC721InvalidSender",
          inputs: [
            {
              name: "sender",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC721NonexistentToken",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "EmptyName",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidSecret",
          inputs: [],
        },
        {
          type: "error",
          name: "NameAlreadyTaken",
          inputs: [
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
          ],
        },
        {
          type: "error",
          name: "NameIsAllWhitespace",
          inputs: [],
        },
        {
          type: "error",
          name: "NameTooLong",
          inputs: [
            {
              name: "length",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "NotYourCommit",
          inputs: [],
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "TooEarlyToReveal",
          inputs: [
            {
              name: "currentBlock",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "minRevealBlock",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 3,
    },
    GiraffeRaceSimulator: {
      address: "0xe1aa25618fa0c7a1cfdab5d6b456af611873b629",
      abi: [
        {
          type: "function",
          name: "simulate",
          inputs: [
            {
              name: "seed",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "winner",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "distances",
              type: "uint16[6]",
              internalType: "uint16[6]",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "simulateWithScore",
          inputs: [
            {
              name: "seed",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "scores",
              type: "uint8[6]",
              internalType: "uint8[6]",
            },
          ],
          outputs: [
            {
              name: "winner",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "distances",
              type: "uint16[6]",
              internalType: "uint16[6]",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "winnerWithScore",
          inputs: [
            {
              name: "seed",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "scores",
              type: "uint8[6]",
              internalType: "uint8[6]",
            },
          ],
          outputs: [
            {
              name: "winner",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "winnersWithScore",
          inputs: [
            {
              name: "seed",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "scores",
              type: "uint8[6]",
              internalType: "uint8[6]",
            },
          ],
          outputs: [
            {
              name: "winners",
              type: "uint8[6]",
              internalType: "uint8[6]",
            },
            {
              name: "winnerCount",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "distances",
              type: "uint16[6]",
              internalType: "uint16[6]",
            },
          ],
          stateMutability: "pure",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 3,
    },
    GiraffeRace: {
      address: "0x196dbcbb54b8ec4958c959d8949ebfe87ac2aaaf",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_giraffeNft",
              type: "address",
              internalType: "address",
            },
            {
              name: "_house",
              type: "address",
              internalType: "address",
            },
            {
              name: "_oddsAdmin",
              type: "address",
              internalType: "address",
            },
            {
              name: "_houseGiraffeTokenIds",
              type: "uint256[6]",
              internalType: "uint256[6]",
            },
            {
              name: "_simulator",
              type: "address",
              internalType: "address",
            },
            {
              name: "_treasury",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "HOUSE_EDGE_BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint16",
              internalType: "uint16",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "LANE_COUNT",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MAX_ENTRIES_PER_RACE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint16",
              internalType: "uint16",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MAX_TICKS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint16",
              internalType: "uint16",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "SPEED_RANGE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "TRACK_LENGTH",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint16",
              internalType: "uint16",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "claim",
          inputs: [],
          outputs: [
            {
              name: "payout",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "claimNextWinningPayout",
          inputs: [],
          outputs: [
            {
              name: "payout",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "createRace",
          inputs: [],
          outputs: [
            {
              name: "raceId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "finalizeRaceGiraffes",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getActiveRaceIdOrZero",
          inputs: [],
          outputs: [
            {
              name: "raceId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getBet",
          inputs: [
            {
              name: "bettor",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "amount",
              type: "uint128",
              internalType: "uint128",
            },
            {
              name: "lane",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "claimed",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getBetById",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "bettor",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "amount",
              type: "uint128",
              internalType: "uint128",
            },
            {
              name: "lane",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "claimed",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getClaimRemaining",
          inputs: [
            {
              name: "bettor",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "remaining",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getNextClaim",
          inputs: [
            {
              name: "bettor",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "out",
              type: "tuple",
              internalType: "struct GiraffeRace.NextClaimView",
              components: [
                {
                  name: "hasClaim",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "raceId",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "status",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "betLane",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "betTokenId",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "betAmount",
                  type: "uint128",
                  internalType: "uint128",
                },
                {
                  name: "winner",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "payout",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "closeBlock",
                  type: "uint64",
                  internalType: "uint64",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getNextWinningClaim",
          inputs: [
            {
              name: "bettor",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "out",
              type: "tuple",
              internalType: "struct GiraffeRace.NextClaimView",
              components: [
                {
                  name: "hasClaim",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "raceId",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "status",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "betLane",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "betTokenId",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "betAmount",
                  type: "uint128",
                  internalType: "uint128",
                },
                {
                  name: "winner",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "payout",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "closeBlock",
                  type: "uint64",
                  internalType: "uint64",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRace",
          inputs: [],
          outputs: [
            {
              name: "closeBlock",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "settled",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "winner",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "seed",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "totalPot",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalOnLane",
              type: "uint256[6]",
              internalType: "uint256[6]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRaceActionabilityById",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "canFinalizeNow",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "canSettleNow",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "closeBlock",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "submissionCloseBlock",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "finalizeEntropyBlock",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "finalizeBlockhashExpiresAt",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "settleBlockhashExpiresAt",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "blocksUntilFinalizeExpiry",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "blocksUntilSettleExpiry",
              type: "uint64",
              internalType: "uint64",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRaceById",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "closeBlock",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "settled",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "winner",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "seed",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "totalPot",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalOnLane",
              type: "uint256[6]",
              internalType: "uint256[6]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRaceDeadHeatById",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "deadHeatCount",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "winners",
              type: "uint8[6]",
              internalType: "uint8[6]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRaceFlagsById",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "settled",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "giraffesFinalized",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "oddsSet",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRaceGiraffes",
          inputs: [],
          outputs: [
            {
              name: "assignedCount",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "tokenIds",
              type: "uint256[6]",
              internalType: "uint256[6]",
            },
            {
              name: "originalOwners",
              type: "address[6]",
              internalType: "address[6]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRaceGiraffesById",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "assignedCount",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "tokenIds",
              type: "uint256[6]",
              internalType: "uint256[6]",
            },
            {
              name: "originalOwners",
              type: "address[6]",
              internalType: "address[6]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRaceOddsById",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "oddsSet",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "decimalOddsBps",
              type: "uint32[6]",
              internalType: "uint32[6]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRaceScheduleById",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "closeBlock",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "submissionCloseBlock",
              type: "uint64",
              internalType: "uint64",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRaceScore",
          inputs: [],
          outputs: [
            {
              name: "score",
              type: "uint8[6]",
              internalType: "uint8[6]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRaceScoreById",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "score",
              type: "uint8[6]",
              internalType: "uint8[6]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getWinningClaimRemaining",
          inputs: [
            {
              name: "bettor",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "remaining",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "giraffeNft",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IGiraffeNFT",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "house",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "houseGiraffeTokenIds",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "laneCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "latestRaceId",
          inputs: [],
          outputs: [
            {
              name: "raceId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "nextRaceId",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "oddsAdmin",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "placeBet",
          inputs: [
            {
              name: "lane",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setRaceOdds",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "decimalOddsBps",
              type: "uint32[6]",
              internalType: "uint32[6]",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "settleRace",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "settledLiability",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "simulate",
          inputs: [
            {
              name: "seed",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "winner",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "distances",
              type: "uint16[6]",
              internalType: "uint16[6]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "simulateWithScore",
          inputs: [
            {
              name: "seed",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "score",
              type: "uint8[6]",
              internalType: "uint8[6]",
            },
          ],
          outputs: [
            {
              name: "winner",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "distances",
              type: "uint16[6]",
              internalType: "uint16[6]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "simulator",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract GiraffeRaceSimulator",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "speedRange",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "submitGiraffe",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "tickCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint16",
              internalType: "uint16",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "trackLength",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint16",
              internalType: "uint16",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "treasury",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract HouseTreasury",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "event",
          name: "BetPlaced",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "bettor",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "lane",
              type: "uint8",
              indexed: true,
              internalType: "uint8",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Claimed",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "bettor",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "payout",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "GiraffeAssigned",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "tokenId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "originalOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "lane",
              type: "uint8",
              indexed: false,
              internalType: "uint8",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "GiraffeSubmitted",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "lane",
              type: "uint8",
              indexed: false,
              internalType: "uint8",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "HouseGiraffeAssigned",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "tokenId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "lane",
              type: "uint8",
              indexed: false,
              internalType: "uint8",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "RaceCreated",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "closeBlock",
              type: "uint64",
              indexed: false,
              internalType: "uint64",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "RaceOddsSet",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "decimalOddsBps",
              type: "uint32[6]",
              indexed: false,
              internalType: "uint32[6]",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "RaceSettled",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "seed",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
            {
              name: "winner",
              type: "uint8",
              indexed: false,
              internalType: "uint8",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "RaceSettledDeadHeat",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "seed",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
            {
              name: "deadHeatCount",
              type: "uint8",
              indexed: false,
              internalType: "uint8",
            },
            {
              name: "winners",
              type: "uint8[6]",
              indexed: false,
              internalType: "uint8[6]",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "AlreadyBet",
          inputs: [],
        },
        {
          type: "error",
          name: "AlreadyClaimed",
          inputs: [],
        },
        {
          type: "error",
          name: "AlreadySettled",
          inputs: [],
        },
        {
          type: "error",
          name: "AlreadySubmitted",
          inputs: [],
        },
        {
          type: "error",
          name: "BettingClosed",
          inputs: [],
        },
        {
          type: "error",
          name: "BettingNotOpen",
          inputs: [],
        },
        {
          type: "error",
          name: "BlockhashUnavailable",
          inputs: [],
        },
        {
          type: "error",
          name: "EntryPoolFull",
          inputs: [],
        },
        {
          type: "error",
          name: "GiraffeNotAssigned",
          inputs: [],
        },
        {
          type: "error",
          name: "GiraffesAlreadyFinalized",
          inputs: [],
        },
        {
          type: "error",
          name: "InsufficientBankroll",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidHouseGiraffe",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidLane",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidOdds",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidRace",
          inputs: [],
        },
        {
          type: "error",
          name: "NoClaimableBets",
          inputs: [],
        },
        {
          type: "error",
          name: "NotHouse",
          inputs: [],
        },
        {
          type: "error",
          name: "NotOddsAdmin",
          inputs: [],
        },
        {
          type: "error",
          name: "NotSettled",
          inputs: [],
        },
        {
          type: "error",
          name: "NotTokenOwner",
          inputs: [],
        },
        {
          type: "error",
          name: "NotWinner",
          inputs: [],
        },
        {
          type: "error",
          name: "OddsAlreadySet",
          inputs: [],
        },
        {
          type: "error",
          name: "OddsNotSet",
          inputs: [],
        },
        {
          type: "error",
          name: "PreviousRaceNotSettled",
          inputs: [],
        },
        {
          type: "error",
          name: "RaceNotReady",
          inputs: [],
        },
        {
          type: "error",
          name: "SubmissionsClosed",
          inputs: [],
        },
        {
          type: "error",
          name: "TokenAlreadyEntered",
          inputs: [],
        },
        {
          type: "error",
          name: "ZeroBet",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 3,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
