/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    YourContract: {
      address: "0x700b6a60ce7eaaea56f065753d8dcb9653dbad35",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_owner",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "receive",
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "greeting",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "premium",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "setGreeting",
          inputs: [
            {
              name: "_newGreeting",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "totalCounter",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "userGreetingCounter",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "withdraw",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "GreetingChange",
          inputs: [
            {
              name: "greetingSetter",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newGreeting",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "premium",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
            {
              name: "value",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 1,
    },
    AnimalNFT: {
      address: "0xa15bb66138824a1c7167f5e85b957d04dd34e468",
      abi: [
        {
          type: "constructor",
          inputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "approve",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "balanceOf",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getApproved",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isApprovedForAll",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
            {
              name: "operator",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "mint",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "mint",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "animalName",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "mint",
          inputs: [
            {
              name: "animalName",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "name",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "nameOf",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "nextTokenId",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "ownerOf",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "safeTransferFrom",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "safeTransferFrom",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "data",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setApprovalForAll",
          inputs: [
            {
              name: "operator",
              type: "address",
              internalType: "address",
            },
            {
              name: "approved",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "supportsInterface",
          inputs: [
            {
              name: "interfaceId",
              type: "bytes4",
              internalType: "bytes4",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "symbol",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "tokenURI",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "tokensOfOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transferFrom",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "Approval",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "approved",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ApprovalForAll",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "operator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "approved",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Transfer",
          inputs: [
            {
              name: "from",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "ERC721IncorrectOwner",
          inputs: [
            {
              name: "sender",
              type: "address",
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC721InsufficientApproval",
          inputs: [
            {
              name: "operator",
              type: "address",
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "ERC721InvalidApprover",
          inputs: [
            {
              name: "approver",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC721InvalidOperator",
          inputs: [
            {
              name: "operator",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC721InvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC721InvalidReceiver",
          inputs: [
            {
              name: "receiver",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC721InvalidSender",
          inputs: [
            {
              name: "sender",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC721NonexistentToken",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 2,
    },
    AnimalRace: {
      address: "0x0c8e79f3534b00d9a3d4a856b665bf4ebc22f2ba",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_animalNft",
              type: "address",
              internalType: "address",
            },
            {
              name: "_house",
              type: "address",
              internalType: "address",
            },
            {
              name: "_houseAnimalTokenIds",
              type: "uint256[4]",
              internalType: "uint256[4]",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "ANIMAL_COUNT",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MAX_ENTRIES_PER_RACE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint16",
              internalType: "uint16",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MAX_TICKS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint16",
              internalType: "uint16",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "SPEED_RANGE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "TRACK_LENGTH",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint16",
              internalType: "uint16",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "animalCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "animalNft",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IERC721",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "claim",
          inputs: [],
          outputs: [
            {
              name: "payout",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "createRace",
          inputs: [],
          outputs: [
            {
              name: "raceId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "finalizeRaceAnimals",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getBet",
          inputs: [
            {
              name: "bettor",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "amount",
              type: "uint128",
              internalType: "uint128",
            },
            {
              name: "animal",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "claimed",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getBetById",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "bettor",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "amount",
              type: "uint128",
              internalType: "uint128",
            },
            {
              name: "animal",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "claimed",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getClaimRemaining",
          inputs: [
            {
              name: "bettor",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "remaining",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getNextClaim",
          inputs: [
            {
              name: "bettor",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "out",
              type: "tuple",
              internalType: "struct AnimalRace.NextClaimView",
              components: [
                {
                  name: "hasClaim",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "raceId",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "status",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "betAnimal",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "betTokenId",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "betAmount",
                  type: "uint128",
                  internalType: "uint128",
                },
                {
                  name: "winner",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "payout",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "closeBlock",
                  type: "uint64",
                  internalType: "uint64",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRace",
          inputs: [],
          outputs: [
            {
              name: "closeBlock",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "settled",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "winner",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "seed",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "totalPot",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalOnAnimal",
              type: "uint256[4]",
              internalType: "uint256[4]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRaceAnimals",
          inputs: [],
          outputs: [
            {
              name: "assignedCount",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "tokenIds",
              type: "uint256[4]",
              internalType: "uint256[4]",
            },
            {
              name: "originalOwners",
              type: "address[4]",
              internalType: "address[4]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRaceAnimalsById",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "assignedCount",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "tokenIds",
              type: "uint256[4]",
              internalType: "uint256[4]",
            },
            {
              name: "originalOwners",
              type: "address[4]",
              internalType: "address[4]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRaceById",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "closeBlock",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "settled",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "winner",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "seed",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "totalPot",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalOnAnimal",
              type: "uint256[4]",
              internalType: "uint256[4]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "house",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "houseAnimalTokenIds",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "latestRaceId",
          inputs: [],
          outputs: [
            {
              name: "raceId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "nextRaceId",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "placeBet",
          inputs: [
            {
              name: "animal",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "settleRace",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "simulate",
          inputs: [
            {
              name: "seed",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "winner",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "distances",
              type: "uint16[4]",
              internalType: "uint16[4]",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "speedRange",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "submitAnimal",
          inputs: [
            {
              name: "tokenId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "tickCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint16",
              internalType: "uint16",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "trackLength",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint16",
              internalType: "uint16",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "event",
          name: "AnimalAssigned",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "tokenId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "originalOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "lane",
              type: "uint8",
              indexed: false,
              internalType: "uint8",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "AnimalSubmitted",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "tokenId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "lane",
              type: "uint8",
              indexed: false,
              internalType: "uint8",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "BetPlaced",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "bettor",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "animal",
              type: "uint8",
              indexed: true,
              internalType: "uint8",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Claimed",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "bettor",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "payout",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "HouseAnimalAssigned",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "tokenId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "lane",
              type: "uint8",
              indexed: false,
              internalType: "uint8",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "RaceCreated",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "closeBlock",
              type: "uint64",
              indexed: false,
              internalType: "uint64",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "RaceSettled",
          inputs: [
            {
              name: "raceId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "seed",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
            {
              name: "winner",
              type: "uint8",
              indexed: false,
              internalType: "uint8",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "AlreadyBet",
          inputs: [],
        },
        {
          type: "error",
          name: "AlreadyClaimed",
          inputs: [],
        },
        {
          type: "error",
          name: "AlreadySettled",
          inputs: [],
        },
        {
          type: "error",
          name: "AlreadySubmitted",
          inputs: [],
        },
        {
          type: "error",
          name: "AnimalNotAssigned",
          inputs: [],
        },
        {
          type: "error",
          name: "AnimalsAlreadyFinalized",
          inputs: [],
        },
        {
          type: "error",
          name: "BettingClosed",
          inputs: [],
        },
        {
          type: "error",
          name: "BettingNotOpen",
          inputs: [],
        },
        {
          type: "error",
          name: "BlockhashUnavailable",
          inputs: [],
        },
        {
          type: "error",
          name: "EntryPoolFull",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidAnimal",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidHouseAnimal",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidRace",
          inputs: [],
        },
        {
          type: "error",
          name: "NoClaimableBets",
          inputs: [],
        },
        {
          type: "error",
          name: "NotSettled",
          inputs: [],
        },
        {
          type: "error",
          name: "NotTokenOwner",
          inputs: [],
        },
        {
          type: "error",
          name: "NotWinner",
          inputs: [],
        },
        {
          type: "error",
          name: "PreviousRaceNotSettled",
          inputs: [],
        },
        {
          type: "error",
          name: "RaceNotReady",
          inputs: [],
        },
        {
          type: "error",
          name: "SubmissionsClosed",
          inputs: [],
        },
        {
          type: "error",
          name: "TokenAlreadyEntered",
          inputs: [],
        },
        {
          type: "error",
          name: "TransferFailed",
          inputs: [],
        },
        {
          type: "error",
          name: "ZeroBet",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 3,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
